### ISSUE TITLE
Info Page is not clear and not accesible to everyone

### ISSUE THREAD

**Issue by crisgarner** [privacy-scaling-explorations/maci-rpgf#94]
This table is not clear and the UI is clunky.

![image](https://github.com/privacy-scaling-explorations/maci-rpgf/assets/578688/e4596370-f4cd-4f64-9c1a-8de037ce3065)

A round status on the main page could help.

![image](https://github.com/privacy-scaling-explorations/maci-rpgf/assets/578688/d7f930d3-edfe-4f4d-a501-39efb750482f)

**Comment by aguzmant103** [comment]
Might be related and fixed in: https://github.com/gitcoinco/easy-retro-pgf/commit/b165c51dd3d3bcaf83e8d931b074d927544504ec

**Comment by crisgarner** [comment]
Seems like this commit doesn't fix the issue, only adds dates to Tallying and Distribution. 
![image](https://github.com/privacy-scaling-explorations/maci-rpgf/assets/578688/f51c5256-0b75-4b38-916b-217b5c09191c)

**Comment by crisgarner** [comment]
New design solves this issue

**Comment by kittybest** [comment]
should be closed by new design https://github.com/privacy-scaling-explorations/maci-rpgf/pull/137
